//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_bazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class autorzy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public autorzy()
        {
            this.ksiazki = new HashSet<ksiazki>();
        }

        [Display(Name = "ID")]
        public int id_autora { get; set; }
        [Display(Name = "Imiê")]
        public string imie { get; set; }
        [Display(Name = "Nazwisko")]
        public string nazwisko { get; set; }
        [Display(Name = "Narodowoœæ")]
        public string narodowosc { get; set; }
        [Display(Name = "Liczba dzie³")]
        public Nullable<int> liczba_dziel { get; set; }
        [Display(Name = "¯yciorys")]
        public string zyciorys { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ksiazki> ksiazki { get; set; }
    }
}
