//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_bazyDanych
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotekaEntities1 : DbContext
    {
        public bibliotekaEntities1()
            : base("name=bibliotekaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autorzy> autorzy { get; set; }
        public virtual DbSet<czytelnicy> czytelnicy { get; set; }
        public virtual DbSet<gatunki> gatunki { get; set; }
        public virtual DbSet<ksiazki> ksiazki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<wydawnictwa> wydawnictwa { get; set; }
        public virtual DbSet<wypozyczenia> wypozyczenia { get; set; }
    }
}
