//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_bazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wypozyczenia
    {
        [Display(Name = "ID")]
        public int id_wypozyczenia { get; set; }
        [Display(Name = "Czytelnik")]
        public Nullable<int> id_czytelnika { get; set; }
        [Display(Name = "Ksi¹¿ka")]
        public Nullable<int> id_ksiazki { get; set; }
        [Display(Name = "Data zamówienia")]
        public Nullable<DateTime> data_zamowienia { get; set; }
        [Display(Name = "Data wypo¿yczenia")]
        public Nullable<DateTime> data_wypozyczenia { get; set; }
        [Display(Name = "Data zwrotu")]
        public Nullable<DateTime> data_zwrotu { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
    
        public virtual czytelnicy czytelnicy { get; set; }
        public virtual ksiazki ksiazki { get; set; }
    }
}
